DROP TABLE IF EXISTS Accommodation CASCADE;

-- Accommodation 테이블 생성
CREATE TABLE Accommodation (
    accommodation_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    accommodation_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


-- Accommodation 더미
INSERT INTO accommodation (name, address, accommodation_type) VALUES
                                                                  ('Sunset Resort', '123 Beach Road, Ocean City', 'RESORT'),
                                                                  ('Mountain View Hotel', '456 Hill Street, Alpine Town', 'HOTEL'),
                                                                  ('Paradise Resort', '789 Island Lane, Paradise Island', 'RESORT'),
                                                                  ('City Central Hotel', '101 Downtown Ave, Metropolis', 'HOTEL'),
                                                                  ('Seaside Resort', '102 Coastal Drive, Shoreline', 'RESORT'),
                                                                  ('Urban Plaza Hotel', '103 Business Street, Metropolis', 'HOTEL'),
                                                                  ('Lakeside Resort', '104 River Bend, Lakeville', 'RESORT'),
                                                                  ('Grand Palace Hotel', '105 Luxury Blvd, Capital City', 'HOTEL'),
                                                                  ('Cedar Forest Resort', '106 Woodlands Road, Forestville', 'RESORT'),
                                                                  ('Skyline Hotel', '107 Skyline Drive, Urbania', 'HOTEL'),
                                                                  ('Ocean Breeze Resort', '108 Ocean Drive, Breezetown', 'RESORT'),
                                                                  ('Royal Garden Hotel', '109 Garden Street, Green City', 'HOTEL'),
                                                                  ('Sunny Beach Resort', '110 Sunshine Blvd, Shoreline', 'RESORT'),
                                                                  ('Highland Hotel', '111 Highland Road, Hillview', 'HOTEL'),
                                                                  ('Palm Tree Resort', '112 Palm Avenue, Tropica', 'RESORT'),
                                                                  ('Silver Springs Hotel', '113 Silver Springs Road, Springsville', 'HOTEL'),
                                                                  ('Emerald Isle Resort', '114 Emerald Isle, Green Bay', 'RESORT'),
                                                                  ('Crystal Waters Hotel', '115 Crystal Road, Waterside', 'HOTEL'),
                                                                  ('Golden Coast Resort', '116 Golden Coast Drive, Seaside', 'RESORT'),
                                                                  ('Royal Park Hotel', '117 Park Avenue, Capital City', 'HOTEL'),
                                                                  ('Blue Horizon Resort', '118 Blue Horizon Road, Horizonville', 'RESORT'),
                                                                  ('Central Plaza Hotel', '119 Central Plaza, Metropolis', 'HOTEL'),
                                                                  ('Sunrise Beach Resort', '120 Sunrise Blvd, Beachside', 'RESORT'),
                                                                  ('Crown Jewel Hotel', '121 Jewel Street, Downtown', 'HOTEL'),
                                                                  ('Lush Garden Resort', '122 Lush Green Road, Green Valley', 'RESORT'),
                                                                  ('City Heights Hotel', '123 City Heights Ave, Urbanville', 'HOTEL'),
                                                                  ('Serene Lake Resort', '124 Lakefront Drive, Laketown', 'RESORT'),
                                                                  ('Capital Tower Hotel', '125 Tower Road, Capital City', 'HOTEL'),
                                                                  ('Sandy Shores Resort', '126 Sandy Shoreline, Beachville', 'RESORT'),
                                                                  ('Metro Grand Hotel', '127 Metro Street, Metropolis', 'HOTEL'),
                                                                  ('Island Escape Resort', '128 Island Drive, Islandtown', 'RESORT'),
                                                                  ('Luxury Palace Hotel', '129 Luxury Lane, Highend City', 'HOTEL'),
                                                                  ('Pine Hills Resort', '130 Pine Hills Road, Woodville', 'RESORT'),
                                                                  ('Sky Tower Hotel', '131 Tower Blvd, Urbania', 'HOTEL'),
                                                                  ('Forest Retreat Resort', '132 Forest Road, Retreatville', 'RESORT'),
                                                                  ('Ocean Pearl Hotel', '133 Pearl Street, Beachside', 'HOTEL'),
                                                                  ('Desert Mirage Resort', '134 Mirage Lane, Desert City', 'RESORT'),
                                                                  ('Cityscape Hotel', '135 Cityscape Drive, Skyline City', 'HOTEL'),
                                                                  ('Tropical Breeze Resort', '136 Breeze Road, Tropica', 'RESORT'),
                                                                  ('Harbor View Hotel', '137 Harbor Street, Port City', 'HOTEL'),
                                                                  ('Mountain Lodge Resort', '138 Mountain Road, Alpine City', 'RESORT'),
                                                                  ('Golden Gate Hotel', '139 Gate Road, Downtown', 'HOTEL'),
                                                                  ('Lakeside Retreat Resort', '140 Lake Drive, Lakeville', 'RESORT'),
                                                                  ('Business Bay Hotel', '141 Business Bay, Metropolis', 'HOTEL'),
                                                                  ('Sunset Lagoon Resort', '142 Lagoon Road, Sunsettown', 'RESORT'),
                                                                  ('Skyline Tower Hotel', '143 Tower Avenue, Cityscape', 'HOTEL'),
                                                                  ('Secluded Haven Resort', '144 Haven Road, Green Valley', 'RESORT'),
                                                                  ('Royal Plaza Hotel', '145 Plaza Street, Capital City', 'HOTEL'),
                                                                  ('Ocean Wave Resort', '146 Wave Blvd, Shoreline', 'RESORT'),
                                                                  ('Downtown Square Hotel', '147 Square Plaza, Metropolis', 'HOTEL'),
                                                                  ('Palm Cove Resort', '148 Palm Cove Drive, Islandtown', 'RESORT'),
                                                                  ('Uptown Grand Hotel', '149 Uptown Road, Capital City', 'HOTEL'),
                                                                  ('White Sands Resort', '150 White Sands Blvd, Seaview', 'RESORT'),
                                                                  ('Elite City Hotel', '151 Elite Street, Urbania', 'HOTEL'),
                                                                  ('Cedar Creek Resort', '152 Cedar Creek Road, Woodville', 'RESORT'),
                                                                  ('Metro Center Hotel', '153 Center Street, Metropolis', 'HOTEL'),
                                                                  ('Sunlit Beach Resort', '154 Sunlit Blvd, Beachside', 'RESORT'),
                                                                  ('Skyview Hotel', '155 Skyview Road, Cityscape', 'HOTEL'),
                                                                  ('Hidden Grove Resort', '156 Grove Street, Green Valley', 'RESORT'),
                                                                  ('Silver City Hotel', '157 Silver Avenue, Urbania', 'HOTEL'),
                                                                  ('Seaside Escape Resort', '158 Escape Road, Shoreline', 'RESORT'),
                                                                  ('Grand Horizon Hotel', '159 Horizon Street, Downtown', 'HOTEL'),
                                                                  ('Blue Waters Resort', '160 Blue Waters Drive, Ocean City', 'RESORT'),
                                                                  ('Capital Crown Hotel', '161 Crown Road, Capital City', 'HOTEL'),
                                                                  ('Golden Shore Resort', '162 Shoreline Road, Golden Beach', 'RESORT'),
                                                                  ('City Tower Hotel', '163 Tower Road, Metropolis', 'HOTEL'),
                                                                  ('Ocean Breeze Resort', '164 Ocean Breeze Blvd, Beachville', 'RESORT'),
                                                                  ('Royal Palm Hotel', '165 Palm Street, Urbania', 'HOTEL'),
                                                                  ('Mountain Top Resort', '166 Mountain Top Road, Alpine Town', 'RESORT'),
                                                                  ('Business Tower Hotel', '167 Tower Street, Capital City', 'HOTEL'),
                                                                  ('Lakeside Hideaway Resort', '168 Hideaway Drive, Lakeville', 'RESORT'),
                                                                  ('Central Tower Hotel', '169 Central Tower, Metropolis', 'HOTEL'),
                                                                  ('Sunset Cove Resort', '170 Cove Road, Sunsettown', 'RESORT'),
                                                                  ('Urban Grand Hotel', '171 Grand Avenue, Capital City', 'HOTEL'),
                                                                  ('Coral Reef Resort', '172 Reef Road, Coral Bay', 'RESORT'),
                                                                  ('Skyline Plaza Hotel', '173 Plaza Street, Cityscape', 'HOTEL'),
                                                                  ('Golden Pine Resort', '174 Pine Road, Woodville', 'RESORT'),
                                                                  ('Metro Park Hotel', '175 Park Avenue, Metropolis', 'HOTEL'),
                                                                  ('Ocean Bay Resort', '176 Ocean Bay Drive, Shoreline', 'RESORT'),
                                                                  ('City Heights Hotel', '177 Heights Avenue, Urbanville', 'HOTEL'),
                                                                  ('Palm Island Resort', '178 Palm Island, Islandtown', 'RESORT'),
                                                                  ('Sky Tower Hotel', '179 Sky Tower Road, Capital City', 'HOTEL'),
                                                                  ('Sunset Paradise Resort', '180 Paradise Road, Beachside', 'RESORT'),
                                                                  ('Harbor City Hotel', '181 Harbor Street, Port City', 'HOTEL'),
                                                                  ('Tropical Sands Resort', '182 Sands Road, Tropica', 'RESORT'),
                                                                  ('Crown Tower Hotel', '183 Tower Blvd, Capital City', 'HOTEL'),
                                                                  ('Ocean Breeze Resort', '184 Ocean Breeze Drive, Seaview', 'RESORT'),
                                                                  ('Elite Tower Hotel', '185 Elite Tower, Urbania', 'HOTEL'),
                                                                  ('Lakeside Serenity Resort', '186 Serenity Drive, Laketown', 'RESORT'),
                                                                  ('Metro Heights Hotel', '187 Heights Blvd, Metropolis', 'HOTEL'),
                                                                  ('Sunrise Bay Resort', '188 Sunrise Bay, Seaside', 'RESORT'),
                                                                  ('City Plaza Hotel', '189 Plaza Avenue, Downtown', 'HOTEL'),
                                                                  ('Ocean Breeze Resort', '190 Seaview Crescent, Beachside', 'RESORT'),
                                                                  ('Sunshine Hotel', '191 Sunny Street, Sunnytown', 'HOTEL'),
                                                                  ('Golden Sands Resort', '192 Golden Beach, Seaview', 'RESORT'),
                                                                  ('Silver Star Hotel', '193 Silver Avenue, Midtown', 'HOTEL'),
                                                                  ('Emerald Bay Resort', '194 Bayfront, Emerald City', 'RESORT'),
                                                                  ('Royal Crown Hotel', '195 Monarch Drive, Downtown', 'HOTEL'),
                                                                  ('Pine Tree Resort', '196 Pine Forest, Woodville', 'RESORT'),
                                                                  ('Crystal Palace Hotel', '197 Crystal Plaza, Capital City', 'HOTEL'),
                                                                  ('Blue Lagoon Resort', '198 Lagoon Lane, Waterside', 'RESORT'),
                                                                  ('Heritage Hotel', '199 Heritage Road, Oldtown', 'HOTEL');